// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("213e5484-5f43-4187-9ef5-3afd19650ba7"),
                            FirstName = "Sebastian",
                            LastName = "Drozd",
                            Telephone = "638334112"
                        },
                        new
                        {
                            Id = new Guid("df7df2c4-005a-4081-a272-c15d0f6fedf4"),
                            FirstName = "Artur",
                            LastName = "Płytkowy",
                            Telephone = "698332444"
                        },
                        new
                        {
                            Id = new Guid("31052f7a-bf2a-47d5-aecb-8dde07f73795"),
                            FirstName = "Piotr",
                            LastName = "Malowniczy",
                            Telephone = "638334112"
                        },
                        new
                        {
                            Id = new Guid("614dc48f-178e-4a2d-a9d8-81589bc64a92"),
                            FirstName = "Kamil",
                            LastName = "Fugowy",
                            Telephone = "638334112"
                        },
                        new
                        {
                            Id = new Guid("c37008c5-34e5-43c7-9a47-3a3a7e883e14"),
                            FirstName = "Karol",
                            LastName = "Szpachlowy",
                            Telephone = "638334112"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
